apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: tobiliba993/vote-service:latest
          ports:
            - containerPort: 80
