grafana:
  enabled: true
  adminPassword: admin
  service:
    type: LoadBalancer
  persistence:
    enabled: true
    size: 2Gi

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: gp2
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
